name: contexts exmaples

on:
  push:
    branches:
      - main

jobs:
    my-contexts:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: echo "Hello, $MY_ACTION"
            - name: Step 2
              run: echo "Hello, $MY_ACTOR"
              env:
                MY_ACTION: ${{ github.action }}
                MY_ACTOR: ${{ github.actor }}