name: Manual Trigger with Parameters

on:
    workflow_dispatch:
        inputs:
            name:
                description: "Name of the person to greet"
                required: true
                type: string
            greeting:
                description: "Type of greeting"
                required: true
                type: string
            data:
                description: "Data to be processed"
                required: false
                type: string

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: Decode File Content
              run: |
                echo "${{ inputs.data }}" | base64 --decode > decoded.txt
            - name: Display Greeting
              run: |
                echo "${{ inputs.greeting }}, ${{ inputs.name }}!"
            - name: Display File Content
              run: |
                echo "Contents of the file:"
                cat ./decoded.txt