name: workflow commands

on:
  push:
    branches:
      - main

jobs:
    workflow-job:
        runs-on: ubuntu-latest
        steps:
            - name: Group Loggins
              run: |
                echo "::group::This is a group of commands"
                echo "This is a command inside the group"
                echo "This is another command inside the group"
                echo "This is the last command inside the group"
                echo "::endgroup::"